### ISSUE TITLE
Issues with build_win.sh

### ISSUE THREAD

**Issue by mhr** [OpenEndedGroup/Field2#105]
Hi,

I tried to install Field2 on my Windows machine and ran into some troubles. I installed babun and ran `build_win.sh`, and this is what I discovered.

1. On L77, `-jdk-home /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/` should be `-jdk-home "C:\Program Files\Java\jdk-9\"`, since /Library/ is Mac directory structure, not Windows
2. Some directories don't exist. For instance, /win/lib/jars/ and /lib/jars/orientdb/

I tried removing those directories from the build script, just to see what would happen (i.e. how far it would get / what sort of error message I would receive), and this is the top few lines of the error message I received:

```
-- building main classes --
warning: classpath entry points to a non-existent location: field_agent.jar:field_linker.jar:..\lib\jars\asm-6.0_ALPHA.jar
warning: classpath entry points to a non-existent location: ..\lib\jars\txtmark-0.14-SNAPSHOT.jar:
error: supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class field.graphics.Scene, unresolved supertypes: AsMap
    class fieldbox.boxes.Box, unresolved supertypes: AsMap
    class field.utility.AsMapDelegator, unresolved supertypes: AsMap
    class field.linalg.Vec2, unresolved supertypes: AsMap_callable
    class field.utility.Dict, unresolved supertypes: AsMap
    class field.utility.Dict.Prop, unresolved supertypes: AsMap
    class field.utility.IdempotencyMap, unresolved supertypes: AsMap
    class field.graphics.Shader, unresolved supertypes: AsMap
    class field.graphics.FLine, unresolved supertypes: AsMap
    class field.graphics.FLine.Node, unresolved supertypes: AsMap
    class field.graphics.MeshBuilder, unresolved supertypes: AsMap_callable

...
```

I hope this helps. If you'd like further information, I would be happy to provide it.

**Comment by marcdownie** [comment]
Looks like build_win and build.sh (on OSX) are lagging behind the IDEA build files. I've just pushed some major improvements to build.sh, and will try to do the same for windows this evening. We'll be moving from cygwin / babun based build_win.sh to a Bash-On-Windows build_win.sh.
