### ISSUE TITLE
Code blocks occasionally save exponentially 

### ISSUE THREAD

**Issue by xaviorlewis** [OpenEndedGroup/Field2#110]
Code blocks saving causes some of the blocks to exceed 2GB's of memory, causing the text editor to crash.

**Comment by marcdownie** [comment]
We're still looking for the culprit here; it seems that some quoting of the contents of an output box causes the size of the output box to double every save.

**Comment by marcdownie** [comment]
This has been fixed by not saving text output in boxes.
