### ISSUE TITLE
Hi guys, does Field2 works or will work on linux?

### ISSUE THREAD

**Issue by hugosoli** [OpenEndedGroup/Field2#112]
Hi guys, does Field2 works or will work on linux?

**Comment by marcdownie** [comment]
Field2 has not been run on Linux for a few years now (I'm afraid WSL has
meant that the studio can get away without any "real" linux boxes).
However, the newbuild branch is simply using the JCEF that's built into the
jetbrains JBR jdk releases, and building JCEF was always by far our biggest
build problem, so I'd actually be surprised if it didn't at least
kinda-sorta-work.

best,

Marc.
