### ISSUE TITLE
Kotlin classes does not seem to compile correctly in IntelliJ

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#113]
When following the build instructions in README.md the compile step fails on all imports of kotlin classes. 
E.g. `Box.java - cannot find symbol :4 `
The error refers to `import field.app.ThreadSync2;`

This issue is related to the IntelliJ setup.

**Comment by marcdownie** [comment]
Are you in the newbuild branch?

**Comment by jharaldson** [comment]
Yes, in the newbuild branch.

**Comment by jharaldson** [comment]
Got it working. 
1. From earlier versions I had checked the box for Delegate IDE build/run actions to Maven. This should not be checked.
2. Had some issues with JBR. There are not very frequent releases of JBR 17 JDK with JCEF for old x86 Mac. Picked a recent JBR with JCEF (fastdebug), which for some reason did not have the CefMediaAccessHandler included. Not sure if this was a mistake. In general some issues with Java in JBR not being signed and Apple throwing an error and asks you to delete the file. Got the JBR working with one of the .pkg files. Not sure if they got the signing correct for the package files or whether my root access solved it.
3. Used the auto-fix for adding deps to the dependencies.
4. Was messing around a bit with seperate compile for Kotlin, which I guess meant that the project settings for the compilation was not followed. Bad idea. Finally used "Build project" and it all worked smoothly.
