### ISSUE TITLE
PhysicsSystem() and other simulation constructors are not defined

### ISSUE THREAD

**Issue by abargher** [OpenEndedGroup/Field2#118]
When attempting to instantiate a new `PhysicsSystem()`, `Boids()`, or `Production()`, I receive a `ReferenceError` stating that these names have not been defined. This error seems to happen on the latest build 43 ([downloaded here](http://openendedgroup.com/field/installation.html)), on both macOS and Windows. 

Perhaps the simulation module/code was not correctly included in build 43?

Below are some screenshots of these errors, taken on macOS (although the behavior is the same on Windows):

<img width="820" alt="Screenshot 2024-04-05 at 5 37 57 PM" src="https://github.com/OpenEndedGroup/Field2/assets/100113732/0d435923-6722-4298-b5c1-0cd08021dacd">
<img width="720" alt="Screenshot 2024-04-05 at 5 38 48 PM" src="https://github.com/OpenEndedGroup/Field2/assets/100113732/458ea769-a690-4aa4-99a2-3e315ba49787">
<img width="705" alt="Screenshot 2024-04-05 at 5 39 08 PM" src="https://github.com/OpenEndedGroup/Field2/assets/100113732/b1a975cc-b3c4-4fe0-97f3-fca1e871098e">

**Comment by marcdownie** [comment]
You (and I’m guessing the Docs) and missing an import.

‘var PhysicsSystem = Java.type(“ … “)’

I’ll update the docs and close.

**Comment by marcdownie** [comment]
You (and I’m guessing the Docs) are missing an import.

`var PhysicsSystem = Java.type("trace.physics.PhysicsSystem")`

I’ll update the docs and close.

**Comment by marcdownie** [comment]
Docs updated — http://openendedgroup.com/field/simulation.html — reopen if it doesn't get you something that works
