### ISSUE TITLE
Finish Hotkeys

### ISSUE THREAD

**Issue by marcdownie** [OpenEndedGroup/Field2#34]
Just pushed da408d5, with these changes:

 * polished up your file handling code in ```RemoteEditor```
 * ```properties.txt``` is now in ```~/.field/properties.txt```
 * file now contains things like

```
ctrl-a:Run_All()
ctrl-b:performCommand("Bridge to Clojure")
```

where the first one is a "JavaScript" command and the second a command in Java.
 * instantiate.js now sends things like "Run_All" in that map as well as the docs and the names
 * ```performCommand``` sends a ```call.commandByName``` message to look up a command by name and run it.

What's needed now is the syncing of the dictionary to an ```extraKeys``` map where ```"ctrl-a":"Run_All()"``` is transformed into:

```
extraKeys = {
...
"ctrl-a":function(cm){ eval("Run_All()") }
...
}
```

(Of course, if you can do it without the eval, all the better). The code in ServerSupport.java is basically correct.

Bonus points:
 * ```properties.txt``` should be ```properties.edn``` and we should use ```new EDN().write(map)``` and ```(Map)new EDN().read(string)``` to serialize and deserialize a ```Map<String, String>```
 * keyboard shortcuts that are in the defined map should appear in the command popup.
 * those "Javascript commands" should actually also appear in the usual ctrl-_ menu
 * we should be able to edit the properties.edn directly in Field (see #16 as well).
 * the file reading and writing logic should go in one class, one place, not, currently one-and-a-half places.

Don't worry about these for now, but if you can do the sync'ing we'll have something functional going forward.

**Comment by marcdownie** [comment]
Ok, new plan: rather than have files with magic syntax, let's make this code work:

```_.root.keybindings("Save all", "ctrl+s")```

**Comment by jharaldson** [comment]
Can't seem to find a 'properties.edn' in ~ /.field

**Comment by marcdownie** [comment]
I'm closing this, since we moved in a different direction. As of 2e1238d the following works:

```javascript
_.root.shortcut.ctrl_alt_f=function(_) _.runCommand("Edit Fragment")
_.root.shortcut.ctrl_alt_v=function(_) _.runCommand("Edit Vertex")
_.root.shortcut.ctrl_alt_g=function(_) _.runCommand("Edit Geometry")
_.root.shortcut.ctrl_alt_c=function(_) _.runCommand("Edit Code")
```
