### ISSUE TITLE
TextEditor not adjusting to Field window size

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#51]
Related to #40.

Test case:
Actions:
1. Set Mac OS X screen resolution to scaled 'More Space'. 
2. Open Field and shrink the Field window to only take up 50% of the display.
3. Save and close Field.
4. Open Field
5. Adjust Field window size to take up around 100% of the screen.
Response:
TextEditor will continue to be the same size throughout the session.

**Comment by marcdownie** [comment]
TextEditor can now shrink vertically: 2e6e9b0e65f2735258e9741602a22360058e8f09
