### ISSUE TITLE
Scroll bar impact, TextEditor not adjusting to Field window size

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#52]
Related to #40, #51.

Test case:
Actions:
1. Set Mac OS X screen resolution to scaled 'More Space'. 
2. Open Field and increase the Field window to only take up 100% of the display.
3. Save and close Field.
4. Open Field
5. Adjust Field window size to take up around 50% of the screen.
6. Add lines to the text editor until the window is full. 
Response:
TextEditor will continue to be the same size throughout the session. The scroll bar will not be triggered since the TextEditor window size is larger than can be seen. The only way of continue adding lines is to again increase the Field window size to 100%.

**Comment by marcdownie** [comment]
TextEditor can now shrink vertically: 2e6e9b0e65f2735258e9741602a22360058e8f09
