### ISSUE TITLE
Evaluating highlighted part of a line

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#53]
Default behavior: 
alt+enter will always evaluate the whole line

Suggested behavior:
alt+enter will evaluate the whole line if no part of the line is highlighted
alt+enter will evaluate only the highlighted part of the line if parts of the line is highlighted

This allows us to evaluate variables and intermediate steps of calculations etc.

**Comment by marcdownie** [comment]
fixed c3b8970
