### ISSUE TITLE
Move quickly between views

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#54]
To quickly move between views, e.g. Code, Vertex, Geometry, Fragment.
Current solution requires the sequence of e.g. 1) ctrl+space 2) f+r+a
Since we move a lot between different views, we would like to minimize the number of keystrokes.

I guess this could be solved with shortcut commands.

**Comment by marcdownie** [comment]
As of 2e1238d the following works:

```javascript
_.root.shortcut.ctrl_alt_f=function(_) _.runCommand("Edit Fragment")
_.root.shortcut.ctrl_alt_v=function(_) _.runCommand("Edit Vertex")
_.root.shortcut.ctrl_alt_g=function(_) _.runCommand("Edit Geometry")
_.root.shortcut.ctrl_alt_c=function(_) _.runCommand("Edit Code")
```
