### ISSUE TITLE
ctrl+c results in all text in window being highlighted

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#62]
Difficult to systematically reproduce. Sometime when trying to copy a code snippet or run all code (alt+0), all text in the window instead gets highlighted. The only way to get back to expected functionality is to either swap between shaders and code or to change box.

**Comment by marcdownie** [comment]
I figured this out only this morning --- the 'a' key is getting stuck down,
and thus ctrl becomes ctrl-a (select all).

toggling 'a' will make the problem vanish.

definitely more trouble in the keycap stuff.

**Comment by marcdownie** [comment]
I wish we had this repeatable. If you can find a recipe for sticking down 'a'...
