### ISSUE TITLE
Evaluation of selected part of line requires a line evaluation first

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#67]
Test case
Actions:
1. Start Field
2. Click box and open code editor
3. Run code in box alt+0
4. Highlight a variable that you would like to evaluate 
5. Evaluate using alt+enter
Results:
1. Nothing happens 

Required is first to evaluate a complete line using alt+enter. After this we can highlight part of a line and run evaluate.

**Comment by jharaldson** [comment]
3. Run code in box alt+0
4. Highlight a variable that you would like to evaluate 
5. Evaluate using alt+enter
Results:
1. Nothing happens 

Required is first to evaluate a complete line using alt+enter. After this we can highlight part of a line and run evaluate.

**Comment by marcdownie** [comment]
I can't duplicate this, but remember fixing a JavaScript WAT in Run_Selected(). Are you sure it's still there?

**Comment by jharaldson** [comment]
It seems to be working, must have used a slightly old build.
