### ISSUE TITLE
Evaluating a python variable results in suitable printout 

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#68]
When evaluating a python variable it would be beneficial to have output of complex structures also printed in output field.

**Comment by jharaldson** [comment]
Showing for example a pandas dataframe requires us to run "print dataframe",  preferred would be that the dataframe is printed out when the variable is evaluated, either by highlighting the variable in a line or having the variable in a separate line and evaluating the whole line.

**Comment by marcdownie** [comment]
This has proved hard to do in jython in the past. In field 1 we had a
keyboard shortcut for "wrap in print(...) and execute that". We could do
option shift enter?

**Comment by jharaldson** [comment]
Sounds good to me
