### ISSUE TITLE
After paste the inserted text is highlighted

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#70]
The inserted text gets highlighted after paste. 
Usually behavior is that the cursor is set to the character just after the pasted text. This could of course be a matter of taste, however, after doing paste usually you want to write something. The benefit of highlighting the text would be that you can quickly go to the position before the inserted text.

**Comment by marcdownie** [comment]
The benefit (you can push left or right arrow after pasting to move to the start and end of the selection) is outweighed by the fact it's different from every other text editor.
