### ISSUE TITLE
Quit application not working (cmd-q and ctrl-c)

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#77]
When trying to quit the application using cmd-Q the application saves and then stalls.
Console output below:

Additional note: Since latest build (4/6/2015) the application no longer responds to ctrl-c.

u                  io.debug :: saving ....
 CEF, getting closed ?
 CEF, getting closed ?
  shutdown on Thread[jcef context thread created by us,5,main]
u                  io.debug :: going to notify ...
u                  io.debug :: ... notified
a            graphics.stats :: meshbuilder cache h8058 | mc0 / meh608 / mih0 / mto0 | tex0
a            graphics.stats :: uploaded 664800 bytes to OpenGL
 frame rate is :20.379619598388672 for fieldbox.ui.FieldBoxWindow@4d9e2229

**Comment by marcdownie** [comment]
duplicates #57, #5
