### ISSUE TITLE
Mouse pointer off in workspace

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#86]
The mouse pointer is off in the whole workspace. I put the mouse pointer in (x,y), but when clicking the actual click is in (x+offset,y). In the scenario with two screens (macbook retina and external non-retina) and running Field on the external screen everything seems to be off.

**Comment by marcdownie** [comment]
Approximately how big is `offset`? Does it change when you pan around?

**Comment by jharaldson** [comment]
It doesn't seem to change when I pan around. 

Attached a screen shot. Imagine that the mouse pointer is in on the left side of the selection area and I have only moved the mouse up on the screen.

![screen shot](https://cloud.githubusercontent.com/assets/7150893/10223970/14fa7386-685c-11e5-8c46-bff395e33dff.png)

**Comment by marcdownie** [comment]
This certainly is completely unexpected, it has to be build related. 

So mouse events are translated by something like 200 pixels to the right? Does it change when you move the window itself (i.e. is there part of your build that's mistaking screen coords for window coords?).

What version of OSX are you on?

**Comment by jharaldson** [comment]
Yes about 200 pixels.

Seems that it runs fine if I move the window a bit on the screen to cancel out the offset. In full screen mode however it seems to work fine.

Running El Capitan.

**Comment by marcdownie** [comment]
Ok, grabbing a non-retina external display to see if I can replicate

**Comment by jharaldson** [comment]
The offset is also there with the retina display on the laptop.

**Comment by marcdownie** [comment]
With no external display?

**Comment by jharaldson** [comment]
Yes, also there without an external screen

**Comment by marcdownie** [comment]
So the only real difference between my hardware and yours is El Capitan. Upgrading a machine now.

**Comment by marcdownie** [comment]
Confirmed. On El Capitan something is converting screen to window coordinates for drags (but not drags) twice. _Think Different_
