### ISSUE TITLE
After code editor window vertical resize two editor windows are visible

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#89]
After code editor window vertical resize two editor windows are visible. The "first" window can be minimized and the "second" will work as intended.

Test case:
1. Start Field
2. Click on a box
3. Resize code editor window vertically by making it smaller

Result:
1. Two code editor windows are visible.
2. The "first" window seems to contain shader code, but does not respond to "ctrl+space"
3. The "second" window seems to include the main code editor and respond to "ctrl+space"

**Comment by marcdownie** [comment]
Can you remove the fieldcef plugins from your ~/.field/plugins.edn file?

Specifically these (OutputBox, TextEditor, TextEditor_boxBrowser,
GlassBrowser). The've become core now. I believe you now have two of all of
them.

Marc

**Comment by jharaldson** [comment]
That solved it.

**Comment by marcdownie** [comment]
Can you remove
